server:
  addr: 0.0.0.0:7001
  readTimeOut: 3s
  writeTimeOut: 3s
  idleTimeOut: 100s

mysql:
  - instance: default
    dsn: root:123456@tcp(localhost:3306)/mall?charset=utf8mb4&loc=Local&parseTime=True&timeout=3s
    trace_log: true # 是否输出所有执行Sql
    slow_threshold: 100 # 慢查询阈值, 单位为ms

postgres:
  dsn: "host=localhost user=postgres password=123456 dbname=ai-image port=5432 sslmode=disable"
  trace_log: true
  slow_threshold: 200
  log: logs/gorm.log
  log_level: 4

logger:
  logFile: logs/mall.log
  logLevel: debug # debug, info, warn, error, dpanic, panic, fatal

jwt:
  api_secret: "api_secret"
  expireTime: 86400 # 单位为秒
  admin_secret: "mall_admin"

redis: 
  addr: localhost:6379
  password: 123456
  db: 0 
  dial_timeout: 100
  read_timeout: 100
  write_timeout: 100
  pool_size: 10
  min_idle_conns: 0
